apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
  labels:
    app: openmrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      containers:
        - name: openmrs
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/openmrs
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-registry-secret
