apiVersion: v1
kind: Service
metadata:
  name: crater-nginx
spec:
  selector:
    app: crater-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
