apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-documents
  labels:
    app: patient-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-documents
  template:
    metadata:
      labels:
        app: patient-documents
    spec:
      containers:
        - name: patient-documents
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/patient-documents
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-registry-secret
