apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
