apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports
  labels:
    app: reports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
        - name: reports
          image: 779846789022.dkr.ecr.ap-south-1.amazonaws.com/reports:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-registry-secret
